// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwplFthA-X28OOP3bRNBlCccYeD96AabI',
    appId: '1:14002696504:web:bba395cc2d0661f54411cd',
    messagingSenderId: '14002696504',
    projectId: 'mynotesapp-1c20f',
    authDomain: 'mynotesapp-1c20f.firebaseapp.com',
    storageBucket: 'mynotesapp-1c20f.firebasestorage.app',
    measurementId: 'G-8YFYRN55T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAq_nyqdnpCVU6beYxJuiVeKHNSQWF04',
    appId: '1:14002696504:android:af8f4e452b39502a4411cd',
    messagingSenderId: '14002696504',
    projectId: 'mynotesapp-1c20f',
    storageBucket: 'mynotesapp-1c20f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUxpr8jys6TSKH5SXyRXDkK_aaBygFcAg',
    appId: '1:14002696504:ios:4d6bdf972b89fcda4411cd',
    messagingSenderId: '14002696504',
    projectId: 'mynotesapp-1c20f',
    storageBucket: 'mynotesapp-1c20f.firebasestorage.app',
    iosBundleId: 'com.example.myNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUxpr8jys6TSKH5SXyRXDkK_aaBygFcAg',
    appId: '1:14002696504:ios:4d6bdf972b89fcda4411cd',
    messagingSenderId: '14002696504',
    projectId: 'mynotesapp-1c20f',
    storageBucket: 'mynotesapp-1c20f.firebasestorage.app',
    iosBundleId: 'com.example.myNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwplFthA-X28OOP3bRNBlCccYeD96AabI',
    appId: '1:14002696504:web:de9d981805c9b1704411cd',
    messagingSenderId: '14002696504',
    projectId: 'mynotesapp-1c20f',
    authDomain: 'mynotesapp-1c20f.firebaseapp.com',
    storageBucket: 'mynotesapp-1c20f.firebasestorage.app',
    measurementId: 'G-7RNKFC8154',
  );

}